export const CREATE_MOVIE_REQUEST = 'CREATE_MOVIE_REQUEST';
export const CREATE_MOVIE_SUCCESS = 'CREATE_MOVIE_SUCCESS';
export const CREATE_MOVIE_ERROR = 'CREATE_MOVIE_ERROR';

export const FETCH_MOVIE_REQUEST = 'FETCH_MOVIE_REQUEST';
export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS';
export const FETCH_MOVIE_ERROR = 'FETCH_MOVIE_ERROR';

export const MOVIE_INFO_REQUEST = 'MOVIE_INFO_REQUEST';
export const MOVIE_INFO_SUCCESS = 'MOVIE_INFO_REQUEST';
export const MOVIE_INFO_ERROR = 'MOVIE_INFO_ERROR';
